build_list7_2: list7_2.cpp
	g++ -std=c++17 -g -Wall list7_2.cpp -o list7_2.out

list7_2: build_list7_2
	./list7_2.out

build_list7_6: list7_6.cpp
	g++ -std=c++17 -g -Wall list7_6.cpp -o list7_6.out

list7_6: build_list7_6
	./list7_6.out

clean:
	rm -rf *.out
