build_list4_2: list4_2.cpp
	g++ -std=c++17 -g -Wall list4_2.cpp -o list4_2.out

list4_2: build_list4_2
	./list4_2.out

build_list4_3: list4_3.cpp
	g++ -std=c++17 -g -Wall list4_3.cpp -o list4_3.out

list4_3: build_list4_3
	./list4_3.out

build_list4_5: list4_5.cpp
	g++ -std=c++17 -g -Wall list4_5.cpp -o list4_5.out

list4_5: build_list4_5
	./list4_5.out

build_list4_12: list4_12.cpp
	g++ -std=c++17 -g -Wall list4_12.cpp -o list4_12.out

list4_12: build_list4_12
	./list4_12.out

build_list4_14: list4_14.cpp
	g++ -std=c++17 -g -Wall list4_14.cpp -o list4_14.out

list4_14: build_list4_14
	./list4_14.out

build_list4_16: list4_16.cpp
	g++ -std=c++17 -g -Wall list4_16.cpp -o list4_16.out

list4_16: build_list4_16
	./list4_16.out

build_list4_27: list4_27.cpp
	g++ -std=c++17 -g -Wall list4_27.cpp -o list4_27.out

list4_27: build_list4_27
	./list4_27.out

build_list4_28: list4_28.cpp
	g++ -std=c++17 -g -Wall list4_28.cpp -o list4_28.out

list4_28: build_list4_28
	./list4_28.out

build_list4_29: list4_29.cpp
	g++ -std=c++17 -g -Wall list4_29.cpp -o list4_29.out

list4_29: build_list4_29
	./list4_29.out

build_list4_30: list4_30.cpp
	g++ -std=c++17 -g -Wall list4_30.cpp -o list4_30.out

list4_30: build_list4_30
	./list4_30.out

clean:
	rm -rf *.out
