build_list3_26: list3_26.cpp
	g++ -std=c++17 -g -Wall list3_26.cpp -o list3_26.out

list3_26: build_list3_26
	./list3_26.out

build_list3_27: list3_27.cpp
	g++ -std=c++17 -g -Wall list3_27.cpp -o list3_27.out

list3_27: build_list3_27
	./list3_27.out

clean:
	rm -rf *.out
