build_list6_10: list6_10.cpp
	g++ -std=c++17 -g -Wall list6_10.cpp -o list6_10.out

list6_10: build_list6_10
	./list6_10.out

build_list6_21: list6_21.cpp
	g++ -std=c++17 -g -Wall list6_21.cpp -o list6_21.out

list6_21: build_list6_21
	./list6_21.out

build_list6_24: list6_24.cpp
	g++ -std=c++17 -g -Wall list6_24.cpp -o list6_24.out

list6_24: build_list6_24
	./list6_24.out

build_list6_25: list6_25.cpp
	g++ -std=c++17 -g -Wall list6_25.cpp -o list6_25.out

list6_25: build_list6_25
	./list6_25.out

clean:
	rm -rf *.out
