build_list9_2: list9_2.cpp
	g++ -std=c++17 -g -Wall list9_2.cpp -o list9_2.out

list9_2: build_list9_2
	./list9_2.out

build_list9_3: list9_3.cpp
	g++ -std=c++17 -g -Wall list9_3.cpp -o list9_3.out

list9_3: build_list9_3
	./list9_3.out

build_list9_4: list9_4.cpp
	g++ -std=c++17 -g -Wall list9_4.cpp -o list9_4.out

list9_4: build_list9_4
	./list9_4.out

build_list9_10: list9_10.cpp
	g++ -std=c++17 -g -Wall list9_10.cpp -o list9_10.out

list9_10: build_list9_10
	./list9_10.out

build_list9_11: list9_11.cpp
	g++ -std=c++17 -g -Wall list9_11.cpp -o list9_11.out

list9_11: build_list9_11
	./list9_11.out

clean:
	rm -rf *.out
