build_list8_3: list8_3.cpp
	g++ -std=c++17 -g -Wall list8_3.cpp -o list8_3.out

list8_3: build_list8_3
	./list8_3.out

build_list8_10: list8_10.cpp
	g++ -std=c++17 -g -Wall list8_10.cpp -o list8_10.out

list8_10: build_list8_10
	./list8_10.out

build_list8_15: list8_15.cpp
	g++ -std=c++17 -g -Wall list8_15.cpp -o list8_15.out

list8_15: build_list8_15
	./list8_15.out

clean:
	rm -rf *.out
