build_list8_3: list8_3.cpp
	g++ -std=c++17 -g -Wall list8_3.cpp -o list8_3.out

list8_3: build_list8_3
	./list8_3.out

build_list8_10: list8_10.cpp
	g++ -std=c++17 -g -Wall list8_10.cpp -o list8_10.out

list8_10: build_list8_10
	./list8_10.out

build_list8_15: list8_15.cpp
	g++ -std=c++17 -g -Wall list8_15.cpp -o list8_15.out

list8_15: build_list8_15
	./list8_15.out

build_list8_23: list8_23.cpp
	g++ -std=c++17 -g -Wall list8_23.cpp -o list8_23.out

list8_23: build_list8_23
	./list8_23.out

build_list8_24: list8_24.cpp
	g++ -std=c++17 -g -Wall list8_24.cpp -o list8_24.out

list8_24: build_list8_24
	./list8_24.out

build_list8_46: list8_46.cpp
	g++ -std=c++17 -g -Wall list8_46.cpp -o list8_46.out

list8_46: build_list8_46
	./list8_46.out

clean:
	rm -rf *.out
