build_list5_2: list5_2.cpp
	g++ -std=c++17 -g -Wall list5_2.cpp -o list5_2.out

list5_2: build_list5_2
	./list5_2.out

build_list5_3: list5_3.cpp
	g++ -std=c++17 -g -Wall list5_3.cpp -o list5_3.out

list5_3: build_list5_3
	./list5_3.out

build_list5_5: list5_5.cpp
	g++ -std=c++17 -g -Wall list5_5.cpp -o list5_5.out

list5_5: build_list5_5
	./list5_5.out

build_list5_6: list5_6.cpp
	g++ -std=c++17 -g -Wall list5_6.cpp -o list5_6.out

list5_6: build_list5_6
	./list5_6.out

clean:
	rm -rf *.out
