build_list5_2: list5_2.cpp
	g++ -std=c++17 -g -Wall list5_2.cpp -o list5_2.out

list5_2: build_list5_2
	./list5_2.out

build_list5_3: list5_3.cpp
	g++ -std=c++17 -g -Wall list5_3.cpp -o list5_3.out

list5_3: build_list5_3
	./list5_3.out

build_list5_5: list5_5.cpp
	g++ -std=c++17 -g -Wall list5_5.cpp -o list5_5.out

list5_5: build_list5_5
	./list5_5.out

build_list5_6: list5_6.cpp
	g++ -std=c++17 -g -Wall list5_6.cpp -o list5_6.out

list5_6: build_list5_6
	./list5_6.out

build_list5_10: list5_10.cpp
	g++ -std=c++17 -g -Wall list5_10.cpp -o list5_10.out

list5_10: build_list5_10
	./list5_10.out

build_list5_12: list5_12.cpp
	g++ -std=c++17 -g -Wall list5_12.cpp -o list5_12.out

list5_12: build_list5_12
	./list5_12.out

build_list5_13: list5_13.cpp
	g++ -std=c++17 -g -Wall list5_13.cpp -o list5_13.out

list5_13: build_list5_13
	./list5_13.out

build_list5_16: list5_16.cpp
	g++ -std=c++17 -g -Wall list5_16.cpp -o list5_16.out

list5_16: build_list5_16
	./list5_16.out

clean:
	rm -rf *.out
